# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem "mysql2"
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: foodtruck
  username: <%= Rails.application.credentials.dig(:database,:development,:username) %>
  password: <%= Rails.application.credentials.dig(:database,:development,:password) %>

test:
  <<: *default
  database: foodtruck_test
  username: <%= Rails.application.credentials.dig(:database,:development,:username) %>
  password: <%= Rails.application.credentials.dig(:database,:development,:password) %>

production:
  <<: *default
  database: foodtruc
  username: <%= Rails.application.credentials.dig(:database,:production,:username) %>
  password: <%= Rails.application.credentials.dig(:database,:production,:password) %>
